# Generated by Django 3.0.14 on 2021-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191220_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nick_name',
            field=models.CharField(default='sdfsdf', max_length=100),
            preserve_default=False,
        ),
    ]
