# Generated by Django 3.0.11 on 2021-03-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='emai',
            new_name='email',
        ),
    ]
