# Generated by Django 3.0.14 on 2021-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='stock_nickname',
            field=models.CharField(default='khan', max_length=100),
            preserve_default=False,
        ),
    ]
